[package]
name = "waiter_map"
version = "0.1.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]

[dependencies]
log = "0.3"
rand = "0.3"
base64 = "0.5"
rust-crypto = "0.2"
may = { git = "ssh://git@gitlab.com/Xudong-Huang/may.git" }